from . import analytics, event_triggers, tronix_integrations
from .triggers import ad_break, automod, ban, bits, charity, command, follow, \
                      goal, hypetrain, message, poll, prediction, raid, redeem, \
                      role, shared_chat, shoutout, sub


def enable_event_triggers(value:bool):
    ad_break.ActionAdBeginTrigger.enabled(value)
    automod.ActionAutomodHoldTrigger.enabled(value)
    automod.ActionAutomodUpdateTrigger.enabled(value)
    ban.ActionBanTrigger.enabled(value)
    ban.ActionUnbanTrigger.enabled(value)
    bits.ActionBitsUseTrigger.enabled(value)
    bits.ActionCheerTrigger.enabled(value)
    charity.ActionChairtyDonateTrigger.enabled(value)
    charity.ActionChairtyStartTrigger.enabled(value)
    charity.ActionChairtyProgressTrigger.enabled(value)
    charity.ActionChairtyStopTrigger.enabled(value)
    command.ActionCommandTrigger.enabled(value)
    follow.ActionFollowTrigger.enabled(value)
    goal.ActionGoalBeginTrigger.enabled(value)
    goal.ActionGoalProgressTrigger.enabled(value)
    goal.ActionGoalEndTrigger.enabled(value)
    hypetrain.ActionHypeTrainBeginTrigger.enabled(value)
    hypetrain.ActionHypeTrainProgressTrigger.enabled(value)
    hypetrain.ActionHypeTrainEndTrigger.enabled(value)
    message.ActionMessageTrigger.enabled(value)
    poll.ActionPollBeginTrigger.enabled(value)
    poll.ActionPollProgressTrigger.enabled(value)
    poll.ActionPollEndTrigger.enabled(value)
    prediction.ActionPredictionBeginTrigger.enabled(value)
    prediction.ActionPredictionProgressTrigger.enabled(value)
    prediction.ActionPredictionLockTrigger.enabled(value)
    prediction.ActionPredictionEndTrigger.enabled(value)
    raid.ActionRaidTrigger.enabled(value)
    redeem.ActionRedeemTrigger.enabled(value)
    role.ActionModAddTrigger.enabled(value)
    role.ActionModRemoveTrigger.enabled(value)
    role.ActionVIPAddTrigger.enabled(value)
    role.ActionVIPRemoveTrigger.enabled(value)
    shared_chat.ActionSharedChatBeginTrigger.enabled(value)
    shared_chat.ActionSharedChatUpdateTrigger.enabled(value)
    shared_chat.ActionSharedChatEndTrigger.enabled(value)
    shoutout.ActionShoutoutCreateTrigger.enabled(value)
    shoutout.ActionShoutoutReceiveTrigger.enabled(value)
    sub.ActionSubTrigger.enabled(value)
    sub.ActionSubMessageTrigger.enabled(value)
    sub.ActionGiftSubTrigger.enabled(value)